export const tips = [
 {
  id:1,
  title:'The right times to observe Mars',
  img:'/TOOLS-IMG/Mars-pic.png',
  fristContent: 'After the Earth passes Mars in its...',
  content:'After the Earth passes Mars in its orbit, Mars gets much further away, and is smaller and dimmer. So the best time to look at Mars is near the opposition time, but, because the orbit of Mars is very elliptical, some oppositions are more favorable that others.',
  images1: '/TOOLS-IMG/Telescopes.png',
  imgContext1: 'Telescopes ',
  images2: '/TOOLS-IMG/Eyepieces.png',
  imgContext2: 'Eyepieces',
  images3: '/TOOLS-IMG/filter.png',
  imgContext3: 'Filters',
 },
 {
  id: 2,
  title: 'the right times to observe mercury',
  img: '/TOOLS-IMG/Mercury.png',
  fristContent: 'When it makes its evening appearances,...',
  content: 'When it makes its evening appearances, the planet is seen above the western horizon shortly after sunset in twilight, and as a morning planet it appears in the east shortly before sunrise. These elongation events mark Mercury\'s best and safest observing periods.',
  imgContext1: 'Telescopes ',
  images1: '/TOOLS-IMG/Telescopes.png',
  imgContext2: 'Eyepieces',
  images2: '/TOOLS-IMG/Eyepieces.png',
  imgContext3: 'Filters',
  images3: '/TOOLS-IMG/filter.png',
 },
 {
  id: 3,
  title: 'the right times to observe jupiter',
  img: '/TOOLS-IMG/jupiter.png',
  fristContent: 'The best time to observe planets...',
  content: 'The best time to observe planets is at night, but Jupiter is so bright that it can sometimes be seen shortly after dusk, and shortly before dawn. At dusk it will rise in the east, but as night goes on Jupiter will appear to travel westwards through the sky.',
  imgContext1: 'Telescopes ',
  images1: '/TOOLS-IMG/Telescopes.png',
  imgContext2: 'Eyepieces',
  images2: '/TOOLS-IMG/Eyepieces.png',
  imgContext3: 'Filters',
  images3: '/TOOLS-IMG/filter.png',
 },
 {
  id: 4,
  title: 'the right times to observe venus',
  img: '/TOOLS-IMG/Venus.png',
  fristContent: 'The easiest way to see Venus in...',
  content: 'The easiest way to see Venus in the daytime is to start when it\'s still night. Find Venus near the sunrise point in the morning. Be sure to position it near a tree, lamppost or building in your foreground. Then keep track of it after the sun rises and the sky turns blue.',
  imgContext1: 'Telescopes ',
  images1: '/TOOLS-IMG/Telescopes.png',
  imgContext2: 'Eyepieces',
  images2: '/TOOLS-IMG/Eyepieces.png',
  imgContext3: 'Filters',
  images3: '/TOOLS-IMG/filter.png',
 },
 {
  id: 5,
  title: 'the right times to observe saturn',
  img: '/TOOLS-IMG/Saturn.png',
  fristContent: 'Saturn is best observed at night,...',
  content: 'Saturn is best observed at night, but it is also visible in the daytime. The best time to observe Saturn is when the planet is in its southern hemisphere, just before sunset. As the sun sets, Saturn will rise in the east and move westward through the sky.',
  imgContext1: 'Telescopes ',
  images1: '/TOOLS-IMG/Telescopes.png',
  imgContext2: 'Eyepieces',
  images2: '/TOOLS-IMG/Eyepieces.png',
  imgContext3: 'Filters',
  images3: '/TOOLS-IMG/filter.png',
 },
 {
  id: 6,
  title: 'the right times to observe uranus',
  img: '/TOOLS-IMG/Uranus.png',
  fristContent: 'Locate a dark spot where you...',
  content: 'Locate a dark spot where you will be able to avoid any contact with light sources for at least 40 minutes. Obviously, this also means timing your observation for a period when the Moon is out of the way. The period between 9–22 November should be ideal.',
  imgContext1: 'Telescopes ',
  images1: '/TOOLS-IMG/Telescopes.png',
  imgContext2: 'Eyepieces',
  images2: '/TOOLS-IMG/Eyepieces.png',
  imgContext3: 'Filters',
  images3: '/TOOLS-IMG/filter.png',
 },
 {
  id: 7,
  title: 'the right times to observe neptune',
  img: '/TOOLS-IMG/Neptune.png',
  fristContent: 'Opposition marks the middle of...',
  content: 'Opposition marks the middle of the best time of the year to see an outer planet. Neptune reaches a yearly maximum in brightness at or near opposition. From mid-July to mid-November, Neptune will be at its brightest but it won\'t be visible to the unaided eye.',
  imgContext1: 'Telescopes ',
  images1: '/TOOLS-IMG/Telescopes.png',
  imgContext2: 'Eyepieces',
  images2: '/TOOLS-IMG/Eyepieces.png',
  imgContext3: 'Filters',
  images3: '/TOOLS-IMG/filter.png',
 },
 {
  id: 8,
  title: 'the right times to observe pluto',
  img: '/TOOLS-IMG/Pluto.png',
  fristContent: 'Pluto is best observed in the...',
  content: 'Pluto is best observed in the early morning or late evening when it is just below the horizon. As the sun sets, Pluto will rise in the east and move westward through the sky. Pluto is also best observed in the summer months, when the planet is at its brightest.',
  imgContext1: 'Telescopes ',
  images1: '/TOOLS-IMG/Telescopes.png',
  imgContext2: 'Eyepieces',
  images2: '/TOOLS-IMG/Eyepieces.png',
  imgContext3: 'Filters',
  images3: '/TOOLS-IMG/filter.png',
 },
 {
  id: 9,
  title: 'the right times to observe a comet',
  img: '/TOOLS-IMG/Comet.png',
  fristContent: 'Comets are visible in the early...',
  content: 'Comets are visible in the early morning and late evening when they are just below the horizon. As the sun sets, comets will rise in the east and move westward through the sky. Comets are also best observed in the summer months, when the planet is at its brightest.',
  imgContext1: 'Telescopes ',
  images1: '/TOOLS-IMG/Telescopes.png',
  imgContext2: 'Eyepieces',
  images2: '/TOOLS-IMG/Eyepieces.png',
  imgContext3: 'Filters',
  images3: '/TOOLS-IMG/filter.png',
 },
 {
  id: 10,
  title: 'the right times to observe a meteor',
  img: '/TOOLS-IMG/Meteor.png',
  fristContent: 'Timing is key when it comes to observing...',
  content: 'Timing is key when it comes to observing meteor showers. The best time is typically during the peak of the shower, which is when Earth passes through the densest part of the debris stream. Late night to early morning hours usually offer the best views.09.07.2024',
  imgContext1: 'Telescopes ',
  images1: '/TOOLS-IMG/Telescopes.png',
  imgContext2: 'Eyepieces',
  images2: '/TOOLS-IMG/Eyepieces.png',
  imgContext3: 'Filters',
  images3: '/TOOLS-IMG/filter.png',
 }
]